services:
  teamcity:
    image: jetbrains/teamcity-server
    container_name: teamcity
    restart: always
    ports:
      - 8111:8111
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs